import Head from "next/head";
import Aside from "@/components/Aside";
import LoadingSpinner from "@/components/LoadingSpinner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingSpinner />
    </>
  );
}
